version: '3'

# Requirements
# traefik: Create ./acme.json file with chmod 600 for lets encrypt
# topgomods: Setup GIHUB_TOKEN env var

services:
  traefik:
    image: traefik:v2.2.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.le.acme.email=anuar@sre.kz"
      - "--certificatesResolvers.le.acme.storage=acme.json"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    labels:
      # global redirect to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
  
      # middleware redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
  

  watchtower:
    image: containrrr/watchtower
    command:
      - "--interval=60"
      - "--label-enable"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  topgomods:
    image: anuar45/topgomods:latest
    restart: always
    networks:
      - web
    environment:
      GITHUB_TOKEN:
    labels:
      - traefik.enable=true
      - traefik.http.routers.topgomods.rule=Host(`topgomods.sre.kz`)
      - traefik.http.routers.topgomods.entrypoints=websecure
      - traefik.http.routers.topgomods.tls=true
      - traefik.http.routers.topgomods.tls.certresolver=le
      - com.centurylinklabs.watchtower.enable=true

  whoami:
    image: containous/whoami
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.sre.kz`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=le
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external: true