version: '3'

# Requirements
# traefik: Create ./acme.json file with chmod 600 for lets encrypt
# topgomods: Setup GIHUB_TOKEN env var
# Install loki docker driver - docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions

networks:
  web:
  loki:

services:
  traefik:
    image: traefik:v2.2.0
    command:
      # - "--api.insecure=true"
      - "--accesslog=true"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.le.acme.email=anuar@sre.kz"
      - "--certificatesResolvers.le.acme.storage=acme.json"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
  
  loki:
    image: grafana/loki:1.4.1
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
      - web

  promtail:
    image: grafana/promtail:1.4.1
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:6.7.3
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - web
    volumes:
      - ./grafana:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.sre.kz`)
      - traefik.http.routers.grafana.entrypoints=web
      - traefik.http.routers.grafana-secure.rule=Host(`grafana.sre.kz`)
      - traefik.http.routers.grafana-secure.entrypoints=websecure
      - traefik.http.routers.grafana-secure.tls=true
      - traefik.http.routers.grafana-secure.tls.certresolver=le
      - traefik.http.middlewares.grafana-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.grafana-redirectscheme.redirectscheme.permanent=true
      - traefik.http.routers.grafana.middlewares=grafana-redirectscheme
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  watchtower:
    image: containrrr/watchtower
    command:
      - "--interval=60"
      - "--label-enable"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  topgomods:
    image: anuar45/topgomods:latest
    restart: unless-stopped
    networks:
      - web
    environment:
      GITHUB_TOKEN:
    labels:
      - traefik.enable=true
      - traefik.http.routers.topgomods.rule=Host(`topgomods.sre.kz`)
      - traefik.http.routers.topgomods.entrypoints=web
      - traefik.http.routers.topgomods-secure.rule=Host(`topgomods.sre.kz`)
      - traefik.http.routers.topgomods-secure.entrypoints=websecure
      - traefik.http.routers.topgomods-secure.tls=true
      - traefik.http.routers.topgomods-secure.tls.certresolver=le
      - traefik.http.middlewares.topgomods-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.topgomods-redirectscheme.redirectscheme.permanent=true
      - traefik.http.routers.topgomods.middlewares=topgomods-redirectscheme
      - com.centurylinklabs.watchtower.enable=true
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  about:
    image: anuar45/about:latest
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.about.rule=Host(`sre.kz`,`www.sre.kz`)
      - traefik.http.routers.about.entrypoints=web
      - traefik.http.routers.about-secure.rule=Host(`sre.kz`,`www.sre.kz`)
      - traefik.http.routers.about-secure.entrypoints=websecure
      - traefik.http.routers.about-secure.tls=true
      - traefik.http.routers.about-secure.tls.certresolver=le
      - traefik.http.middlewares.about-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.about-redirectscheme.redirectscheme.permanent=true
      - traefik.http.routers.about.middlewares=about-redirectscheme
      - com.centurylinklabs.watchtower.enable=true
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  whoami:
    image: containous/whoami
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.sre.kz`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami-secure.rule=Host(`whoami.sre.kz`)
      - traefik.http.routers.whoami-secure.entrypoints=websecure
      - traefik.http.routers.whoami-secure.tls=true
      - traefik.http.routers.whoami-secure.tls.certresolver=le
      - traefik.http.middlewares.whoami-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.whoami-redirectscheme.redirectscheme.permanent=true
      - traefik.http.routers.whoami.middlewares=whoami-redirectscheme
      - com.centurylinklabs.watchtower.enable=true
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

