global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: traefik
    static_configs:
      - targets: ['traefik:8080']

  - job_name: node_exporter
    static_configs:
      - targets: ['do01.sre.kz:9100','oci01.sre.kz:9100','oci02.sre.kz:9100']
