version: '3'

services:
  ci:
    image: drone/drone:1
    restart: always
    labels:
      - "traefik.enable=true" 
    expose:
      - "80"
    volumes:
      - /var/lib/drone:/data
    environment:
      DRONE_AGENTS_ENABLED: "true"
      DRONE_GITHUB_SERVER: "https://github.com"
      DRONE_GITHUB_CLIENT_ID:
      DRONE_GITHUB_CLIENT_SECRET:
      DRONE_RPC_SECRET: "8e70404c3f68f1dd3a999b297b778797"
      DRONE_SERVER_HOST: "ci.zerg.kz"
      DRONE_SERVER_PROTO: "http"